export const oemSpanishPage = {
  slug: 'oem-activewear-manufacturer',
  eyebrow: 'FABRICANTE OEM DE ROPA DEPORTIVA',
  title: 'Fabricante OEM de Ropa Deportiva: Del Tech Pack a la Producción',
  seoTitle: 'Fabricante OEM de Ropa Deportiva | Del Tech Pack a Producción',
  description: 'Desarrolla ropa deportiva OEM personalizada con Fitclo a partir de un tech pack o brief de referencia. Planifica producto, tejidos, tallas, muestras, etiquetas, embalaje, inspección y producción.',
  heroTitle: 'Convierte un brief de producto aprobado en un programa OEM de ropa deportiva.',
  heroText: 'La fabricación OEM es adecuada para compradores que necesitan sus propios detalles de producto: silueta, medidas, tejido, colores, avíos, marca y embalaje. Fitclo ayuda a estructurar las decisiones antes del muestreo y la producción.',
  productCodes: ['TZ4510-14', 'TZ4506-4', 'TZ2557-6'],
  fabricNotes: [
    'Parte de la función prevista de la prenda y documenta tejido exterior, forro, elásticos, malla, avíos y colores.',
    'Usa muestras físicas y una prenda aprobada para confirmar tacto, cobertura, elasticidad y recuperación.',
    'Mantén la dirección de materiales aprobada entre la evaluación de la muestra y la planificación de producción.',
  ],
  sizeNotes: [
    'Proporciona una talla base, puntos de medida, tolerancias y criterios de escalado siempre que estén disponibles.',
    'Utiliza un paquete técnico o un brief de referencia documentado en lugar de depender únicamente de una imagen.',
    'Evalúa tallas representativas cuando el rango o la construcción del producto lo requieran.',
  ],
  decisionRows: [
    ['Información de desarrollo', '¿Tienes tech pack, muestra aprobada o solo una referencia?', 'Archivos, medidas, detalles funcionales y cantidad objetivo.'],
    ['Construcción del producto', '¿Qué tejido, costuras, forro, avíos y detalles funcionales se requieren?', 'Orientación de BOM, vistas y notas de construcción.'],
    ['Aprobación de muestra', '¿Qué debe aprobarse antes de la producción?', 'Ajuste, material, color, logo, etiquetas y referencia de embalaje.'],
    ['Preparación de producción', '¿Qué debe estar alineado para el pedido y el envío?', 'Cantidad, surtido de tallas, avíos de marca, inspección y destino.'],
  ],
  qualityChecks: [
    'Confirma la muestra frente al brief de producto documentado antes de aprobar la producción.',
    'Revisa tejido, medidas, elasticidad, costuras, avíos y detalles funcionales en la talla y el color seleccionados.',
    'Comprueba logo, etiquetas, etiquetas colgantes, embalaje y datos de cajas frente a la referencia aprobada.',
    'Utiliza controles de inspección y revisión final del embalaje acordes con los requisitos confirmados del pedido.',
  ],
  faqs: [
    { question: '¿Qué es la fabricación OEM de ropa deportiva?', answer: 'Es una modalidad en la que el comprador aporta o aprueba requisitos específicos como diseño, materiales, medidas, marca y embalaje, y el fabricante desarrolla y produce conforme a ese brief.' },
    { question: '¿Puedo iniciar un proyecto OEM sin un tech pack completo?', answer: 'Puedes comenzar con referencias y objetivos de producto, pero un brief técnico más claro reduce ambigüedades. Fitclo puede ayudarte a identificar la información necesaria antes del muestreo.' },
    { question: '¿Qué debo aprobar antes de la producción?', answer: 'Aprueba la muestra correspondiente, tejido, medidas, color, construcción, ubicación del logo, etiquetas, etiquetas colgantes y requisitos de embalaje en una referencia documentada.' },
    { question: '¿Cuál es el MOQ para producción OEM?', answer: 'El MOQ se confirma según diseño, tejido, colores, rango de tallas, avíos y alcance de personalización. Los modelos elegibles de stock disponible tienen una lógica independiente de 50 unidades o 50 sets.' },
    { question: '¿Fitclo puede ayudar con el embalaje y la inspección?', answer: 'Sí. Comparte el brief de embalaje y los puntos de calidad relevantes para incorporarlos a la evaluación de muestras y a la planificación de producción.' },
  ],
  catalogPath: '/products/',
  catalogLabel: 'Ver opciones de productos deportivos',
  productTranslations: {
    'TZ4510-14': { name: 'Conjunto Deportivo de 3 Piezas para Mujer', description: 'Conjunto de chaqueta, leggings y sujetador deportivo para yoga, Pilates, gimnasio y colecciones de marca privada.' },
    'TZ4506-4': { name: 'Conjunto Capri Halter con Ribete de Contraste', description: 'Chaleco halter y leggings capri 7/8 de cintura media en nylon-spandex, con ribetes y franjas laterales de contraste.' },
    'TZ2557-6': { name: 'Conjunto sin Costuras con Top Halter y Leggings Flare', description: 'Top halter de punto sin costuras y leggings flare de cintura alta para Pilates, yoga, estudio y programas de marca privada.' },
  },
};

export const oemSpanishTranslations = [
  ['MOQ logic', 'Opciones de MOQ'], ['Sample review', 'Evaluación de muestras'], ['Private label options', 'Opciones de marca privada'],
  ['View Product Directions', 'Ver opciones de productos'], ['Discuss on WhatsApp', 'Hablar por WhatsApp'], ['BUYER STARTING POINT', 'PUNTO DE PARTIDA PARA COMPRADORES'],
  ['Select a product route and target quantity.', 'Selecciona una modalidad de producto y la cantidad objetivo.'], ['Share fabric, color and size direction.', 'Comparte tus preferencias de tejido, color y tallas.'],
  ['Confirm sample, logo and packaging requirements.', 'Confirma los requisitos de muestra, logo y embalaje.'], ['Approve the product and quality reference before bulk.', 'Aprueba el producto y la referencia de calidad antes de la producción.'],
  ['Ready-stock qualifying sets start from 50 sets; individual garments start from 50 pcs. Custom routes are reviewed against the brief.', 'Los conjuntos de stock disponible comienzan desde 50 sets y las prendas individuales desde 50 unidades. Los proyectos personalizados se evalúan según el brief.'],
  ['BRANDING', 'MARCA'], ['Discuss logo, labels, hang tags and packaging with the selected product route.', 'Define logo, etiquetas, etiquetas colgantes y embalaje según la modalidad elegida.'],
  ['SAMPLES', 'MUESTRAS'], ['Confirm the appropriate sample option before approving fit, color, construction and branding.', 'Confirma la opción de muestra adecuada antes de aprobar ajuste, color, confección y marca.'],
  ['RELATED PRODUCT DIRECTIONS', 'OPCIONES DE PRODUCTOS RELACIONADOS'], ['Start from relevant product references.', 'Empieza con referencias de producto relevantes.'],
  ['BUYER DECISION FRAMEWORK', 'MARCO DE DECISIÓN DEL COMPRADOR'], ['Turn an idea into a workable sourcing brief.', 'Convierte una idea en un brief de abastecimiento viable.'],
  ['A clear brief lets a buyer compare a selected ready-stock route with a more custom development route without treating them as the same offer.', 'Un brief claro permite comparar una opción de stock disponible con un desarrollo más personalizado sin tratarlos como la misma oferta.'],
  ['DECISION', 'DECISIÓN'], ['BUYER QUESTION', 'PREGUNTA DEL COMPRADOR'], ['RECORD BEFORE SAMPLE', 'DEFINIR ANTES DE LA MUESTRA'],
  ['FABRIC &amp; SIZE PLANNING', 'PLANIFICACIÓN DE TEJIDOS Y TALLAS'], ['Choose the direction, then validate it on the right sample.', 'Elige la dirección y valídala con la muestra adecuada.'],
  ['SIZE &amp; FIT RECORD', 'REGISTRO DE TALLA Y AJUSTE'], ['Read the sizing &amp; grading guide', 'Leer la guía de tallaje y escalado'], ['Read the sizing &amp; grading guide →', 'Leer la guía de tallaje y escalado →'],
  ['SAMPLING, PRODUCTION &amp; QUALITY', 'MUESTRAS, PRODUCCIÓN Y CALIDAD'], ['Approve the reference before you approve the production route.', 'Aprueba la referencia antes de autorizar la producción.'],
  ['The sequence is practical: agree the product and sample route, document changes, confirm the approval reference, then plan bulk, inspection, packing and shipment details. Production timing is confirmed against the actual order requirements rather than promised as a generic page number.', 'La secuencia es práctica: define el producto y la muestra, documenta cambios, confirma la referencia aprobada y después planifica producción, inspección, embalaje y envío. Los plazos se confirman según los requisitos reales del pedido.'],
  ['Use the activewear sample approval checklist', 'Usar la lista de aprobación de muestras'], ['Use the activewear sample approval checklist →', 'Usar la lista de aprobación de muestras →'], ['READY-STOCK ROUTE', 'OPCIÓN DE STOCK DISPONIBLE'],
  ['Need to assess the current program first?', '¿Necesitas evaluar primero el programa actual?'], ['Use the Ready-Stock Activewear Catalog to filter qualifying programme styles. Current colors and size mixes are confirmed before order, and logo, label, hang tag, packaging and sample options are discussed against the chosen style.', 'Usa el catálogo de stock disponible para filtrar modelos elegibles. Los colores y combinaciones de tallas se confirman antes del pedido, y las opciones de logo, etiquetas, embalaje y muestras se revisan según el modelo elegido.'],
  ['Open Ready-Stock Catalog', 'Abrir catálogo de stock disponible'], ['WHAT TO SEND FOR A CURRENT CHECK', 'QUÉ ENVIAR PARA COMPROBAR DISPONIBILIDAD'],
  ['Selected style or product direction, estimated quantity and destination.', 'Modelo u orientación de producto, cantidad estimada y destino.'], ['Preferred colors, size mix and whether a sample is required.', 'Colores, combinación de tallas y necesidad de muestra.'],
  ['Logo artwork, placement, labels, hang tags or packaging requirements.', 'Archivo y ubicación del logo, etiquetas, etiquetas colgantes o requisitos de embalaje.'], ['Required launch or delivery planning context, without assuming a generic lead-time promise.', 'Contexto de lanzamiento o entrega, sin asumir un plazo genérico.'],
  ['BUYER FAQ', 'PREGUNTAS FRECUENTES DE COMPRADORES'], ['Questions to settle before the order moves forward.', 'Preguntas que conviene resolver antes de avanzar con el pedido.'],
  ['REQUEST PRODUCT DIRECTION', 'SOLICITAR ORIENTACIÓN DE PRODUCTO'], ['Get a practical recommendation for your next collection.', 'Recibe una recomendación práctica para tu próxima colección.'],
  ['Send your product type, target quantity, fabric direction, size range, branding requirements and delivery context. Fitclo will help organize the next sourcing questions.', 'Envía el tipo de producto, cantidad objetivo, tejido, rango de tallas, requisitos de marca y contexto de entrega. Fitclo te ayudará a organizar los siguientes pasos de abastecimiento.'],
  ['Ask on WhatsApp', 'Consultar por WhatsApp'], ['INQUIRY ROUTE', 'VÍA DE CONSULTA'], ['Use the form below to request selected styles, a sample discussion, logo options, packaging or a current ready-stock check.', 'Usa el formulario para solicitar modelos, evaluar una muestra, consultar opciones de logo y embalaje o comprobar stock disponible.'], ['Open Inquiry Form', 'Abrir formulario de consulta'],
] as const;
